# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

import cam


class Ui_MainWindow(object):
    def __init__(self):
        self.MainWindow: QtWidgets.QMainWindow
        self.MainWindow = None

    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setWindowModality(Qt.ApplicationModal)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 675)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 675))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 675))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1200, 675))
        self.centralwidget.setMaximumSize(QtCore.QSize(1200, 675))
        self.centralwidget.setBaseSize(QtCore.QSize(1200, 675))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gameFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameFrame.sizePolicy().hasHeightForWidth())
        self.gameFrame.setSizePolicy(sizePolicy)
        self.gameFrame.setMinimumSize(QtCore.QSize(960, 540))
        self.gameFrame.setMaximumSize(QtCore.QSize(960, 540))
        self.gameFrame.setBaseSize(QtCore.QSize(0, 0))
        self.gameFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.gameFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gameFrame.setLineWidth(2)
        self.gameFrame.setMidLineWidth(0)
        self.gameFrame.setObjectName("gameFrame")
        self.horizontalLayout_5.addWidget(self.gameFrame)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(6, -1, 6, 6)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.breathType = QtWidgets.QLabel(self.centralwidget)
        self.breathType.setObjectName("breathType")
        self.horizontalLayout_3.addWidget(self.breathType)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.breathRate = QtWidgets.QLabel(self.centralwidget)
        self.breathRate.setObjectName("breathRate")
        self.horizontalLayout_4.addWidget(self.breathRate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.cameraButton = QtWidgets.QPushButton(self.centralwidget)
        self.cameraButton.setObjectName("cameraButton")
        self.verticalLayout_4.addWidget(self.cameraButton)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 6)
        self.verticalLayout_4.setStretch(3, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.cameraFrame = QtWidgets.QFrame(self.centralwidget)
        self.cameraFrame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraFrame.sizePolicy().hasHeightForWidth())
        self.cameraFrame.setSizePolicy(sizePolicy)
        self.cameraFrame.setMinimumSize(QtCore.QSize(240, 135))
        self.cameraFrame.setMaximumSize(QtCore.QSize(240, 135))
        self.cameraFrame.setSizeIncrement(QtCore.QSize(0, 0))
        self.cameraFrame.setBaseSize(QtCore.QSize(0, 0))
        self.cameraFrame.setAutoFillBackground(False)
        self.cameraFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.cameraFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cameraFrame.setObjectName("cameraFrame")
        self.verticalLayout_5.addWidget(self.cameraFrame)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.cameraButton.clicked.connect(self.open_camera)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Тип дыхания: "))
        self.breathType.setText(_translate("MainWindow", "Тип+цвет"))
        self.label_2.setText(_translate("MainWindow", "Частота дыхания: "))
        self.breathRate.setText(_translate("MainWindow", "Число+цвет"))
        self.cameraButton.setText(_translate("MainWindow", "Включить камеру"))

    def open_camera(self):
        self.MainWindow.setVisible(False)
        cam.main()
        self.MainWindow.setVisible(True)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
